### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by kaieberl** [namtranase/gemma-cpp-python#3]
Hi, thanks for building this!
Could you maybe have a look at this error upon `pip install pygemma`:
```
Collecting pygemma
  Downloading pygemma-0.1.0.tar.gz (3.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygemma
  Building wheel for pygemma (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pygemma (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running bdist_wheel
      running build
      running build_ext
      CMake Warning:
        Ignoring extra path from command line:
      
         "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-install-5p_blrjo/pygemma_e39722359cdf49649c38ba1285a1a47d"
      
      
      CMake Error: The source directory "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-install-5p_blrjo/pygemma_e39722359cdf49649c38ba1285a1a47d" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Traceback (most recent call last):
        File "/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 56, in <module>
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-build-env-yzu0w6m1/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 25, in run
        File "<string>", line 47, in build_extension
        File "/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-install-5p_blrjo/pygemma_e39722359cdf49649c38ba1285a1a47d', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/jr/td9rb8x92llg9mmgn92sw8ch0000gn/T/pip-install-5p_blrjo/pygemma_e39722359cdf49649c38ba1285a1a47d/build/lib.macosx-11.0-arm64-cpython-311', '-DPYTHON_EXECUTABLE=/Users/k/opt/miniconda3/envs/paper2audio/bin/python']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygemma
```

System: macOS 14.3.1 on Macbook Air M2
Python 3.11

**Comment by namtranase** [comment]
Thank you for using the pygemma. I'm trying to reproduce on MacOS, will be back soon when the problem is solved.

**Comment by namtranase** [comment]
Hi @kaieberl, I just updated a new version and checked on my Mac M1. Please re-install it and check it, if any issue happens I will be active to fix it!

**Comment by kaieberl** [comment]
Thank you for the quick reply!
The pip version still doesn't work, I believe there is a path hardcoded:
```
    import pygemma
ImportError: dlopen(/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pygemma.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libsentencepiece.0.dylib
  Referenced from: <8539844B-F260-394C-A674-B4806D746344> /Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pygemma.cpython-311-darwin.so
  Reason: tried: '/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/Users/k/opt/miniconda3/envs/paper2audio/bin/../lib/libsentencepiece.0.dylib' (no such file), '/Users/k/opt/miniconda3/envs/paper2audio/bin/../lib/libsentencepiece.0.dylib' (no such file)
```
However, it works when I compile the wheel from source.

**Comment by namtranase** [comment]
Oh my bad, I will check it more carefully.

**Comment by namtranase** [comment]
Hi @kaieberl, I just pushed a new version. Hopefully, it will solve the pip install problem.

**Comment by namtranase** [comment]
We just pushed a new version v0.1.3 which improved the user interface. Welcome to all comments if you use it!

**Comment by kaieberl** [comment]
I just tried to pip install again. Now installation works, but `from pygemma import Gemma` throws an error.
I tried `pip uninstall pygemma`, then `pip install pygemma`. Here is the output:
Traceback (most recent call last):
```
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pygemma.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libsentencepiece.0.dylib
  Referenced from: <F53C1CFE-CD3C-3F96-9457-ADEACB1110A8> /Users/k/opt/miniconda3/envs/paper2audio/lib/python3.11/site-packages/pygemma.cpython-311-darwin.so
  Reason: tried: '/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/namtran/workspace/personal/playground/gemma-cpp-python/build/lib.macosx-11.1-arm64-cpython-311/libsentencepiece.0.dylib' (no such file), '/Users/k/opt/miniconda3/envs/paper2audio/bin/../lib/libsentencepiece.0.dylib' (no such file), '/Users/k/opt/miniconda3/envs/paper2audio/bin/../lib/libsentencepiece.0.dylib' (no such file)
```
It still includes your workspace name.
Any ideas what else I could try?

**Comment by namtranase** [comment]
Hi @kaieberl, I just added the patch version: 0.1.3.post3, which tries to solve this error. The problem is the libsentencepiece.0.dylib needs to `delocate-wheel` before pushing to the pypi. You can try it again, thank you!
