### ISSUE TITLE
Failed building wheel for pygemma

### ISSUE THREAD

**Issue by insightfully** [namtranase/gemma-cpp-python#6]
Hey there, I get an error when running `pip install pygemma`

This seems to be similar to [an issue raised 2 weeks ago ](https://github.com/namtranase/gemma-cpp-python/issues/3)

I'm running on windows 11 using Python 3.12.2 

```
Collecting pygemma
  Using cached pygemma-0.1.2.tar.gz (4.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pygemma
  Building wheel for pygemma (pyproject.toml): started
  Building wheel for pygemma (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for pygemma (pyproject.toml) did not run successfully.
  exit code: 1

  [63 lines of output]
  running bdist_wheel
  running build
  running build_ext
  CMake Warning:
    Ignoring extra path from command line:

     "C:\Users\user\AppData\Local\Temp\pip-install-wkyx2b9t\pygemma_0078c98a806c4d5b81a7ca4d10006f36"


  CMake Error: The source directory "C:/Users/user/AppData/Local/Temp/pip-install-wkyx2b9t/pygemma_0078c98a806c4d5b81a7ca4d10006f36" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Traceback (most recent call last):
    File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 56, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-jq82rw7z\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 25, in run
    File "<string>", line 47, in build_extension
    File "C:\Python312\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-wkyx2b9t\\pygemma_0078c98a806c4d5b81a7ca4d10006f36', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\7\\AppData\\Local\\Temp\\pip-install-wkyx2b9t\\pygemma_0078c98a806c4d5b81a7ca4d10006f36\\build\\lib.win-amd64-cpython-312', '-DPYTHON_EXECUTABLE=C:\\Python312\\python.exe']' returned non-zero exit status 1.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygemma
Failed to build pygemma
ERROR: Could not build wheels for pygemma, which is required to install pyproject.toml-based projects
```

**Comment by namtranase** [comment]
Hi @insightfully, thank for using the package. We will check it again and be back when everything is in the window.

**Comment by namtranase** [comment]
Hi @insightfully, we just released a new version, could you check it again and give us feedback?
For window, I think you can refer to the [system requirements ](https://github.com/google/gemma.cpp?tab=readme-ov-file#system-requirements)in the gemma.cpp for better installation. Feel free to add any comments

**Comment by insightfully** [comment]
I've tried the installation again after double checking that I installed the gemma.cpp requirements and encountered the same error.

My guess is that this might be a problem specific to the way the project uses cmake in windows

**Comment by namtranase** [comment]
Thank you for the feedback. If the problem is happening with the gemma.cpp also, can you make an issue on the gemma.cpp, we will carefully check it with the gemma.cpp authors.

**Comment by namtranase** [comment]
Thank @phamson02 for the [PR](https://github.com/namtranase/gemma-cpp-python/pull/11), I think we can support Window now. @insightfully can you try it and give us your feedback?

**Comment by namtranase** [comment]
No problem @insightfully. We will figure out the way to install it. Do you try to install from the source (we haven't released the new version via pip yet, so it is better if you can try the pip install .). Otherwise, could you give us the log?

**Comment by insightfully** [comment]
It worked, Adding `ClangCL`  via visual studio (instead of only build tools) seems to have fixed the problem
